---

name: Build and Deploy GoScript

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'

      - name: Enable Go modules
        run: |
          echo "export GO111MODULE=on" >> $GITHUB_ENV
          go mod init main.go || true

      - name: Install dependencies
        run: go get -v github.com/Code-Hex/Neo-cowsay/v2

      - name: run cowsay main.go
        run: go run main.go

      - name: Build the executable
        run: |
          go build -o myapp-cowsay-go main.go
          ls -al 
          file myapp-cowsay-go 

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-artifact@v4 # or specific "vX.X.X" version tag for this action
        with:
          path: myapp-cowsay-go
          name: myapp-cowsay-go

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: see user who deploy
        run: whoami
      - uses: actions/download-artifact@v4
        with:
          path: /var/www/html/
          name: myapp-cowsay-go