name: Nightly Docker Build

on:
  schedule:
    # Planifier l'exécution tous les jours à minuit UTC
    - cron: '0 0 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
    # Étape 1 : Vérifier le code source du dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2 : Connexion au registre Docker
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.COWSAY_GO_USR }}
        password: ${{ secrets.COWSAY_GO_MD }}

    # Étape 3 : Construire l'image Docker
    - name: Build Docker image
      run: docker build -t christasd/myapp-cowsay-go:latest .

    # Étape 4 : Taguer et pousser l'image
    - name: Push Docker image
      run: |
        docker tag christasd/myapp-cowsay-go:latest christasd/myapp-cowsay-go:$(date +'%Y%m%d')
        docker push christasd/myapp-cowsay-go:latest
        docker push christasd/myapp-cowsay-go:$(date +'%Y%m%d')
